name: PlaytimesX
main: com.playtimesx.Main
version: 1.0
author: ajan_12
description: >
             A plugin for making playtime dependant ranks.
commands:
   playtime:
      description: Checks the player''s current playtime information
      usage: To see your own playtime (/playtime) or to see someone else''s playtime information(/playtime <playername>).