name: SlimefunFix
version: ${project.version}
main: top.ageofelysian.slimefunfix.SlimefunFix
authors: [ajan_12]
depend: [CS-CoreLib, Slimefun, ExoticGarden]
description: A plugin that fixes broken slimefun items.
commands:
  slimefunfix:
    description: Opens a gui where players can fix their broken slimefun items.
    aliases: sffix
    usage: /slimefunfix <help|gui>